#spring.main.allow-bean-definition-overriding=true
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50 #percentage
        wait-duration-in-open-state: 10s
spring:
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      - "qa"
  application:
    name: accounts
  jpa:
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
  info:
    env:
      enabled: true
info:
  message: "welcome to accounts application default profile"
  name: "raj default profile accounts"
